#!/usr/bin/env python3
import subprocess
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"
_MODULE = _PROGRAM_DIR.name.replace("-", "_")
_MODULE_DIR = _PROGRAM_DIR / _MODULE
_TESTS_DIR = _PROGRAM_DIR / "tests"

if _VENV_DIR.exists():
    context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
    python_exe = context.env_exe
else:
    python_exe = "python3"

_TARGETS = [str(_MODULE_DIR), str(_TESTS_DIR)]

subprocess.check_call([python_exe, "-m", "black", *_TARGETS, "--check"])
subprocess.check_call([python_exe, "-m", "isort", *_TARGETS, "--check"])
subprocess.check_call([python_exe, "-m", "flake8", *_TARGETS])
subprocess.check_call([python_exe, "-m", "pylint", *_TARGETS])
subprocess.check_call([python_exe, "-m", "mypy", *_TARGETS])
